### ISSUE TITLE
Key Error: "tokenize"

### ISSUE THREAD

**Issue by Remorax** [adithya7/lambre#17]
Hi,

Thank you for your excellent work and for sharing the code.

There seems to be a bug that causes lambre (tested by calling it from bash) to crash. Here is the error output:

```
Traceback (most recent call last):
  File "/rds/project/rds-48gU72OtDNY/cs-iyer1/miniconda3/envs/fairseq2/bin/lambre", line 8, in <module>
    sys.exit(main())
  File "/rds/project/rds-48gU72OtDNY/cs-iyer1/miniconda3/envs/fairseq2/lib/python3.8/site-packages/lambre/metric.py", line 313, in main
    if args["tokenize"] and not args["ssplit"]:
KeyError: 'tokenize'
```

Removing `args["tokenize"]` seems to work - however, I am not sure if it is the most optimal solution (maybe `args["tokenize"]` was previously used elsewhere?). Could I please request you to look into it?

Thanks in advance!

**Comment by adithya7** [comment]
Thanks for catching this! We always tokenize the input, so this option is no longer necessary.

It should be fixed now.
